### ISSUE TITLE
Where is the macOS and iOS versions of the app?

### ISSUE THREAD

**Issue by pr0gramm3r101** [lollipopkit/flutter_server_box#770]
I want to use this app on macOS and iOS, but i don't see the app in Releases.

I saw that you commented out the GitHub Actions job for Apple platforms:

```yml
releaseApple:
  name: Release ios and macos
  runs-on: macos-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Flutter
      uses: subosito/flutter-action@v2
with:
  channel: 'stable'
  flutter-version: '3.22.2'
    - name: Build
      run: dart run fl_build -p ios,mac
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ env.APP_NAME }}_universal_macos.zip
          ${{ env.APP_NAME }}_universal.ipa
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I can build the app myself with `flutter build macos` but it would be more convenient to just download the app from the release.
